name: update-gh-activity

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Update README with recent activity
        uses: jamesgeorge007/github-activity-readme@master
        with:
          GH_USERNAME: Hanserq
          COMMIT_MSG: "chore: update recent activity"
          COMMIT_NAME: "github-actions[bot]"
          COMMIT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
          MAX_LINES: 5
          TARGET_FILE: "README.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
